version: "3.9"
services:
  corba-server:
    build:
      context: ../
      dockerfile: CORBA/Dockerfile
    container_name: corba-server
    volumes:
      - ../CORBA:/app/CORBA:rw
    command: ["sh", "-c", "omniidl -bpython hello.idl || true; python server.py"]
  corba-client:
    build:
      context: ../
      dockerfile: CORBA/Dockerfile
    container_name: corba-client
    depends_on:
      - corba-server
    volumes:
      - ../CORBA:/app/CORBA:rw
    command: ["tail", "-f", "/dev/null"]